language: node_js
node_js:
  - "8"
dist: trusty
addons:
  apt:
    packages:
      - libopencv-dev
script:
  - npm test
  - codecov
notifications:
  slack:
    rooms:
      - hpi:ndJzCSHEaofBnyHTHURo0DFO
    on_success: change
    on_pull_requests: false
    template:
          - "Build <%{build_url}|#%{build_number}> of *%{branch}* by %{author} %{result}."
          - "(<%{compare_url}|%{commit}>) _%{commit_message}_"
  email: false
