language: node_js
node_js:
  - "8"
dist: trusty
addons:
  apt:
    packages:
      - libopencv-dev
      - ghostscript
script:
  - npm test
  - codecov
notifications:
  slack: hpi:ndJzCSHEaofBnyHTHURo0DFO