language: node_js
node_js:
  - "8"
dist: trusty
addons:
  apt:
    packages:
      - libopencv-dev
script:
  - npm test
  - codecov
notifications:
  slack:
    rooms:
      - hpi:ndJzCSHEaofBnyHTHURo0DFO
    on_success: change
    on_pull_requests: false
    template:
          - "Build <%{build_url}|#%{build_number}> of <%{compare_url}|%{branch}> by %{author} %{result}."
          - "> %{commit_message}"
  email: false
