version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /tmp/pichasso
