version: '2'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    command: npm run production
    restart: always
    environment:
      NODE_ENV: production
    ports:
      - 80:3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /tmp/pichasso:/tmp/imagecache
